version: "3.9"

services:
    trainer :
      build: "./ml-loan-demo"
      volumes: 
        - mlops_loan-model-data:/data
        - mlops_loan-model:/models
      profiles: ["trainer"]

    # api:
    #   build: "./loan-api"
    #   ports: 
    #     - "8000:8000"
    #   volumes: 
    #     - loan-model:/models
    #   depends_on:
    #     - trainer 
  
volumes:
  mlops_loan-model:
  mlops_loan-model-data: